PREFIX mo: <http://purl.org/ontology/mo/>
PREFIX mood: <http://sovarr.c4dm.eecs.qmul.ac.uk/moodplay/>

SELECT ?valence ?arousal ?mbid ?path
WHERE 
{
  SELECT ?valence ?arousal ?mbid ?path ((ABS(@valence-?valence) + ABS(@arousal-?arousal)) as ?diff) 
  WHERE {
    ?coords mood:valence ?valence ;
      mood:arousal ?arousal ;
      mood:configuration mood:actfold4 .
    ?lfmid mood:coordinates ?coords ;
      mo:available_as ?fileid ;
      mo:musicbrainz_guid ?mbid .
    ?fileid mood:filename ?path .
    
  } ORDER BY ?diff
} LIMIT 1